// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXSjSG5r5n3ToITt5nmzwSMAnnmg_lFBY',
    appId: '1:931689805337:web:fe14cd5d555f540efd5c88',
    messagingSenderId: '931689805337',
    projectId: 'chat-app-dff2f',
    authDomain: 'chat-app-dff2f.firebaseapp.com',
    storageBucket: 'chat-app-dff2f.firebasestorage.app',
    measurementId: 'G-D9C570QJLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0lYuIDxM-GzHLW5H-imf9Tq2v4RaQA4M',
    appId: '1:931689805337:android:8a5a7f4076f4be73fd5c88',
    messagingSenderId: '931689805337',
    projectId: 'chat-app-dff2f',
    storageBucket: 'chat-app-dff2f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXSjSG5r5n3ToITt5nmzwSMAnnmg_lFBY',
    appId: '1:931689805337:web:65ad57d775c8724efd5c88',
    messagingSenderId: '931689805337',
    projectId: 'chat-app-dff2f',
    authDomain: 'chat-app-dff2f.firebaseapp.com',
    storageBucket: 'chat-app-dff2f.firebasestorage.app',
    measurementId: 'G-RGPGCQ71NZ',
  );
}
